name: Build

on:
  push:
    branches:
      - dev


jobs:
  build:
    name: Build and analyze
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
              -Dsonar.projectKey=DEVOPS
              -Dsonar.projectName=DEVOPS
              -Dsonar.projectVersion=1.0.0
              -Dsonar.sources=.
