name: primeiro-workflow # nome tecnico
run-name: Primeiro Workflow #nome leitura mais simples

#on:
#   - push
on: [push]

jobs:
    mac:
        runs-on: macos-latest
        steps: 
            - name: Hello World
              run: echo "Deu bom!"
    
    linux:
        runs-on: unbutu-latest
        steps: 
            - name: Hello World
              run: echo "Deu bom tbm"
    

